In [1]:
#friend 객체에 값을 할당하기
friend = 1
type(friend)

int

In [2]:
#연산을 이용해 원과 삼각형의 넓이 구하기
r = 2
circle_area = 3.14 * (r**2)
x = 3
y = 4
triangle_area = x * y / 2
print (circle_area, triangle_area)

12.56 6.0


In [3]:
#문자열 계산하기
'py' 'thon'
'py' + 'thon'
'py' * 3

'pypypy'

In [4]:
a = "파이썬"
a[1]
a[1:4]
a[:]
a[::2] # 처음부터 2칸 간격으로 값 출력

'파썬'

In [6]:
#값의 형태를 변환하기
# 실수형에서 문자열로 변환
a = str(3.14)
a

'3.14'

In [7]:
a + 1 # 문자열에 숫자를 더하면 타입 에러가 발생한다.

TypeError: can only concatenate str (not "int") to str

In [8]:
#문자열에서 정수로 변환
b = int("49")
b

49

In [9]:
b + 11

60

In [10]:
#정수형에서 실수형으로 변환
c = float(23)
c

23.0

In [11]:
c + 0.9

23.9

In [12]:
#함수 정의하고 연산하기

#함수 정의
def Times(a, b):
    a = a + 1 #같은 함수의 내용은 들여쓰기가 같다
    b = b + 1
    return a * b

In [14]:
Times(10, 10)

121

In [15]:
#return이 없으면 None을 반환하는 것을 확인
def setValue(newValue):
    x = newValue
    retval = setValue(10)
    print(retval)

In [16]:
#반복문 사용하기
for i in [1,2,3,4]:
    print(i)

1
2
3
4


In [20]:
for i in range(1,5): # 1부터 5미만의 숫자를 리스트로 자동으로 만드는 range 함수
    print(i)

1
2
3
4


In [21]:
#리스트 안에 for를 포함하여 실습하기
a = [1,2,3,4]
result = []
for num in a:
    result.append(num * 3)

In [22]:
result = [num * 3 for num in a]

In [23]:
print(result)

[3, 6, 9, 12]


In [24]:
#리스트 a의 값 중에서 2로 나눈 나머지가 0인 수만 3을 곱해 리스트 result에 넣는다
result = [num * 3 for num in a if num % 2 == 0]

In [25]:
print(result)

[6, 12]


In [26]:
#리스트 만들기
clr_names = ['red', 'green', 'gold']
type(clr_names) # 자료 구조의 종류를 알려줌

list

In [27]:
#리스트에 값 추가하기
clr_names.append('blue')
clr_names

['red', 'green', 'gold', 'blue']

In [29]:
#리스트에 0부터 시작할 위치를 지정하여 값 추가하기
clr_names.insert(1, 'black')
clr_names

['red', 'black', 'black', 'green', 'gold', 'blue']

In [30]:
t = (1, 2, 3)
type(t)
a, b = 1, 2
(a, b) = (1, 2)
print(a, b)

1 2


In [31]:
a, b = b, a
print(a, b)

2 1


In [32]:
# in 연산자를 이용해 값 확인하기
a = set((1, 2, 3))
type(a)

set

In [33]:
1 in a

True

In [34]:
c = tuple(a)
type(c)

tuple

In [35]:
3 in c

True

In [37]:
#딕셔너리 만들기
d = dict(a = 1, b = 3, c = 5) #dict로 딕셔너리 생성
type(d)

dict

In [38]:
clr_names = {"apple":"red", "banana":"yellow"}
clr_names

{'apple': 'red', 'banana': 'yellow'}

In [39]:
clr_names["apple"]

'red'

In [40]:
clr_names[0] #인덱싱을 지원하지 않는다.

KeyError: 0

In [41]:
clr_names["cherry"] = "red" #값 추가
clr_names

{'apple': 'red', 'banana': 'yellow', 'cherry': 'red'}

In [42]:
#numpy의 array 함수를 쓰기 위해 numpy패키지를 np라는 이름으로 불러오기
import numpy as np
a = np.array([0, 1, 2, 3, 4, 5])
a.ndim # ndim은 a의 차원 수를 알려준다

1

In [43]:
#배열 a의 각 차원에 몇개의 값이 있는지를 튜플로 반환한다. 값 6개를 갖는 1차원 배열은 다음처럼 표현
a.shape

(6,)

In [44]:
# 배열 a의 값들의 타입을 알려주며, 아래 결과는 정수(integer)임을 의미한다
a.dtype

dtype('int32')

In [45]:
#기본 인덱싱
a[[2, 3, 4]]
array([2, 3, 4])

array([2, 3, 4])

In [47]:
# 배열을 인덱싱으로 사용할 수 있다.
a[np.array([2, 3, 4])]

array([2, 3, 4])

In [48]:
# 배열 중 원하는 값 출력하기 위해 논리 연산하기
a > 4

array([False, False, False, False, False,  True])

In [49]:
a[a > 4]

array([5])

In [50]:
#배열의 기본 활용 연습하기
x = [0.0, 1, 2, 3, 4]
y = np.array(x) #0.0으로 인해 다른 1, 2, 3, 4도 모두 실수형으로 변경되어 배열을 생성
y = np.array([[0.0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
np.shape(y) #행과 열을 확인

(2, 5)

In [51]:
y = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
np.shape(y) #2개의 2차원 배열, 각 2차원 배열은 2행 2열임을 순서대로 의미

(2, 2, 2)

In [54]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for x in a:
    print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [55]:
#배열에서 슬라이싱 하기
#1차원에서 0~9까지의 정수가 실수형으로 변환한 후 2행 5열 형태로 표현
arr = np.arange(10, dtype = float).reshape((2, 5))
arr[0] #1행

array([0., 1., 2., 3., 4.])

In [56]:
arr[0, 3] #1행 3열

3.0

In [57]:
arr[0][3]

3.0

In [58]:
arr[0, :]

array([0., 1., 2., 3., 4.])

In [59]:
arr[:, 0]

array([0., 5.])

In [60]:
#판다스의 시리즈와 데이터프레임을 임포트하기
from pandas import Series, DataFrame
s = Series([0.1, 1.2, 2.3, 3.4, 4.5], index = ['a','b','c','d','e'])
s['a']

0.1

In [61]:
s[0]

0.1

In [62]:
s[['a', 'c']]

a    0.1
c    2.3
dtype: float64

In [63]:
s[[0, 2]]

a    0.1
c    2.3
dtype: float64

In [64]:
s[s > 2]

c    2.3
d    3.4
e    4.5
dtype: float64

In [65]:
s1 = Series({'a': 0.1, 'b': 1.2, 'c': 2.3})
s2 = Series({'a': 1.0, 'b': 2.0, 'c': 3.0})
s1 + s2

a    1.1
b    3.2
c    5.3
dtype: float64

In [67]:
s1 = Series(np.arange(10.0, 20.0))
s1.describe() # 시리즈 s1의 요약 정보 출력

count    10.00000
mean     14.50000
std       3.02765
min      10.00000
25%      12.25000
50%      14.50000
75%      16.75000
max      19.00000
dtype: float64

In [70]:
summ = s1.describe()
summ['mean'] #요약 값 중에서 mean 항목 값을 출력

14.5

In [71]:
s1 = Series(np.arange(1.0, 6), index = ['a','a','b','c','d'])
s1.drop('a') #시리즈에서 index가 a인 값을 제외

b    3.0
c    4.0
d    5.0
dtype: float64

In [74]:
#데이터 프레임을 다양하게 생성해보기
from pandas import Series, DataFrame
raw_data = {'col0':[1, 2, 3, 4],
           'col1':[10, 20, 30, 40],
           'col2':[100, 200, 300, 400]}
data =DataFrame(raw_data)
print(data)

   col0  col1  col2
0     1    10   100
1     2    20   200
2     3    30   300
3     4    40   400


In [75]:
a = np.array([[1.0, 2], [3, 4]])
df = DataFrame(a, columns=['dogs', 'cats'], index= ['Alice', 'Bob'])
print(df)

       dogs  cats
Alice   1.0   2.0
Bob     3.0   4.0


In [76]:
import pandas as pd
#값의 구분자를 \t라는 탭 문자로, 생성할 파일의 인코딩을 utf-8로 지정
df.to_csv('c:/test.csv', sep = '\t', encoding = 'utf-8')
writer = pd.ExcelWriter('c:/test.xlsx')
df.to_excel(writer, 'DataFrame')
writer.save()

PermissionError: [Errno 13] Permission denied: 'c:/test.csv'

In [1]:
#numpy, scipy 이용해 다양한 선형대수 연산하기
import numpy as np
from scipy import linalg, sparse

In [2]:
A = np.matrix(np.random.random((2, 2)))
b = np.random.random((2, 2))
B = np.asmatrix(b)
C = np.mat(np.random.random((10, 5)))
D = np.mat([[3, 4], [5, 6]]) # 2차원 자료를 나타낸 리스트를 행렬로 표현

In [3]:
print(A)

[[0.0967617  0.86474896]
 [0.16914054 0.00806199]]


In [4]:
print(B)

[[0.02811455 0.2922685 ]
 [0.63154583 0.02129727]]


In [5]:
print(D)

[[3 4]
 [5 6]]


In [6]:
A.I # A의 역행렬

matrix([[-0.05541495,  5.9439448 ],
        [ 1.16260567, -0.66510194]])

In [7]:
linalg.det(A) # A의 행렬식

-0.1454840159384483

In [8]:
A.T #A의 전치행렬

matrix([[0.0967617 , 0.16914054],
        [0.86474896, 0.00806199]])

In [9]:
np.add(A, D) # A와 D의 합

matrix([[3.0967617 , 4.86474896],
        [5.16914054, 6.00806199]])

In [10]:
np.subtract(A, D) # A와 D의 차

matrix([[-2.9032383 , -3.13525104],
        [-4.83085946, -5.99193801]])

In [11]:
np.divide(A, D) # A 나누기 D

matrix([[0.0322539 , 0.21618724],
        [0.03382811, 0.00134366]])

In [12]:
print(D@B) # D와 B의 행렬곱을 @로 계산

[[2.61052696 0.96199457]
 [3.92984771 1.5891261 ]]


In [13]:
print(np.dot(D, B)) #D와 B의 행렬곱을 numpy의 dot 함수로도 계산할 수 있다.

[[2.61052696 0.96199457]
 [3.92984771 1.5891261 ]]


In [14]:
print(np.multiply(D, B)) #행렬 D와 B에 대해서, 행렬곱이 아닌 대응되는 원소끼리의 단순 곱셈 수행

[[0.08434365 1.16907398]
 [3.15772913 0.12778362]]


In [16]:
G = np.mat(np.identity(2)) # 2x2 항등행렬
G

matrix([[1., 0.],
        [0., 1.]])

In [17]:
linalg.eigvals(A) # 행렬 A의 고윳값 확인

array([ 0.43741966+0.j, -0.33259597+0.j])

In [18]:
la, v = linalg.eig(A) #A의 고유 벡터

In [19]:
l1, l2 = la #고유값을 l1, l2로 받기

In [20]:
v[: ,0] #첫 번째 고유 벡터

array([0.93040866, 0.36652385])

In [21]:
v[:,1] # 두번째 고유 벡터

array([-0.89567358,  0.44471209])

In [22]:
C[C > 0.5] = 0

In [23]:
H = sparse.csr_matrix(C) # C를 희소행렬 형태로 변환

In [24]:
H.todense()

matrix([[0.09370808, 0.14056213, 0.31030879, 0.        , 0.21349526],
        [0.07023883, 0.        , 0.        , 0.18563381, 0.43082645],
        [0.27976513, 0.        , 0.        , 0.        , 0.39048052],
        [0.01653561, 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.06750647, 0.28566097],
        [0.        , 0.        , 0.15975035, 0.        , 0.00191707],
        [0.        , 0.        , 0.11864229, 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.00444054],
        [0.04866109, 0.10828018, 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.1896508 , 0.        , 0.        ]])

In [25]:
sparse.isspmatrix_csr(H)

True

In [2]:
import sympy as sp

In [3]:
x = sp.Symbol('x')

In [4]:
print(sp.diff(3 * x**2 + 1, x)) # **는 파이썬에서 차수를 의미

6*x


In [5]:
from scipy.misc import derivative
def f(x):                #원래 함수 정의
    return 3*x**2+1
def d(x):
    return derivative(f, x) #미분한 함수
print(d(2.0))

12.0


In [6]:
import sympy as sp
x = sp.Symbol('x')
sp.integrate(3.0*x**2+1, x)


1.0*x**3 + 1.0*x

In [7]:
import numpy as np
from scipy.integrate import quad

def f(x):
    return 3.0*x**2 +1
i = quad(f, 0, 2)
print(i[0])

10.000000000000002


In [9]:
from scipy.optimize import fsolve
import numpy as np
line = lambda x: x + 3
solution = fsolve(line, -2) # 해를 -2부터 찾기 시작한다
print(solution)

[-3.]


In [10]:
def f(x): #함수 정의
    return (x**3 -1) # x = 1에서 하나의 해 존재
from scipy import optimize #사이파이에서 optimize 모듈 불러오기

In [11]:
# x축의 1.5값 지점에서 시작하여 뉴턴랩슨 메서드로 x의 해를 구함
root = optimize.newton(f, 1.5)
print(root)

1.0000000000000016


In [12]:
root = optimize.newton(f, 1.5, fprime = lambda x : 3 * x **2)
print(root)

1.0


In [13]:
# f의 미분된 함수를 또 미분한 함수를 표시
root = optimize.newton(f, 1.5, fprime2 = lambda x: 6 * x)
print(root)

1.0000000000000016


In [14]:
root = optimize.newton(f, 1.5, fprime = lambda x: 3* x**2, fprime2 = lambda x: 6 * x)
print(root)

1.0


In [15]:
cur_x = 3 # x = 3에서 계산 시작
rate = 0.01 # 학습률
precision = 0.000001 # 반복 계산에 사용할 기준 (tolerance rate)
previous_step_size = 1
max_iters = 10000 #최대 반복 횟수 10000
iters = 0 # 반복 횟수를 기록하기 위해 생성, 0 부터 시작
df = lambda x: 2*(x + 5) #현재 예제에서 함수의 기울기

In [16]:
while (previous_step_size > precision) and (iters < max_iters):
    prev_x = cur_x # 현재 x를 이전 단계 x로 저장
    cur_x = cur_x - rate * df(prev_x) # 경사 하강법 계산
    previous_step_size = abs(cur_x - prev_x) # x값의 변화
    iters = iters+1 # 반복 카운터 증가

In [17]:
print("국소 최솟값은?", cur_x)

국소 최솟값은? -4.9999518490318176


In [18]:
#3x제곱 +1 미분하기
import sympy as sp
x = sp.Symbol('x')
sp.diff(3.0*x**2 + 1, x)

6.0*x

In [19]:
#미분 개념을 활용하여 미분한 x + 3 함수가 0이 되는 해 찾기
from scipy.optimize import fsolve
import numpy as np
line = lambda x: x + 3
solution = fsolve(line, -2)
print(solution)

[-3.]


In [20]:
#x제곱을 적분하고 0~3 사이의 적분 값 찾기
import numpy as np
from scipy.integrate import quad

In [21]:
# 적분할 함수 정의
func = lambda x: np.cos(np.exp(x))**2

In [22]:
# 0부터 3까지의 구간에 대해 함수 func를 적분
solution = quad(func, 0, 3)
print(solution)
# 첫 번째 값은 적분, 두 번째 값은 오차

(1.296467785724373, 1.3977971853986262e-09)


In [23]:
#sin(x) + cos(x제곱) + 1 함수를 적분하고 구간 0~5의 적분 값 찾기
import numpy as np
from scipy.integrate import quad
x = np.sort(np.random.randn(150) * 4 + 4).clip(0, 5) # 0~5 사이의 랜덤한 값 생성
func = lambda x: np.sin(x) * np.cos(x**2) + 1 #적분할 함수
y = func(x)

In [24]:
fsolution = quad(func, 0, 5) # 함수 quad로 적분하기
print(fsolution)

(5.100345067540932, 1.2589916837356385e-08)
