## 학습목표
 1. numpy에서 자주 사용되는 함수들을 사용해보기

In [1]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.94864156 0.25056117 0.0702284  0.13198904 0.3110229 ]
 [0.52921254 0.97902426 0.53119967 0.82408661 0.93226386]
 [0.42951263 0.61011294 0.66171711 0.13500774 0.96223173]]


#### 연산 함수
 - add, substract, multiply, divide

In [3]:
np.add(x, y)

array([[ 0.94864156,  1.25056117,  2.0702284 ,  3.13198904,  4.3110229 ],
       [ 5.52921254,  6.97902426,  7.53119967,  8.82408661,  9.93226386],
       [10.42951263, 11.61011294, 12.66171711, 13.13500774, 14.96223173]])

In [4]:
np.divide(x, y)

array([[ 0.        ,  3.99104136, 28.47850529, 22.72916002, 12.86078933],
       [ 9.44799986,  6.12855092, 13.17771912,  9.70771746,  9.65391922],
       [23.28220263, 18.02944865, 18.13463755, 96.2907769 , 14.54950979]])

In [5]:
x + y

array([[ 0.94864156,  1.25056117,  2.0702284 ,  3.13198904,  4.3110229 ],
       [ 5.52921254,  6.97902426,  7.53119967,  8.82408661,  9.93226386],
       [10.42951263, 11.61011294, 12.66171711, 13.13500774, 14.96223173]])

In [6]:
x / y

array([[ 0.        ,  3.99104136, 28.47850529, 22.72916002, 12.86078933],
       [ 9.44799986,  6.12855092, 13.17771912,  9.70771746,  9.65391922],
       [23.28220263, 18.02944865, 18.13463755, 96.2907769 , 14.54950979]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [7]:
print(y)

[[0.94864156 0.25056117 0.0702284  0.13198904 0.3110229 ]
 [0.52921254 0.97902426 0.53119967 0.82408661 0.93226386]
 [0.42951263 0.61011294 0.66171711 0.13500774 0.96223173]]


In [8]:
np.mean(y)

0.5537874778485802

In [9]:
y.mean()

0.5537874778485802

In [10]:
np.max(y)

0.9790242556731885

In [11]:
np.argmax(y)

6

In [12]:
np.var(y), np.median(y), np.std(y)

(0.09928327408978284, 0.5311996661999381, 0.3150924849782724)

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [13]:
y

array([[0.94864156, 0.25056117, 0.0702284 , 0.13198904, 0.3110229 ],
       [0.52921254, 0.97902426, 0.53119967, 0.82408661, 0.93226386],
       [0.42951263, 0.61011294, 0.66171711, 0.13500774, 0.96223173]])

In [14]:
np.sum(y, axis=None)

8.306812167728703

In [15]:
np.cumsum(y)

array([0.94864156, 1.19920273, 1.26943114, 1.40142018, 1.71244308,
       2.24165562, 3.22067988, 3.75187954, 4.57596615, 5.50823001,
       5.93774264, 6.54785559, 7.2095727 , 7.34458044, 8.30681217])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [16]:
z = np.random.randn(10)
print(z)

[-0.61953399  0.72552309  0.26810584  1.78793455 -0.09996493 -1.23695566
  1.82649556  0.25418552  0.36427494  0.57529603]


In [17]:
z > 0

array([False,  True,  True,  True, False, False,  True,  True,  True,
        True])

In [18]:
np.any(z > 0)

True

In [19]:
np.all(z != 0)

True

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [20]:
z = np.random.randn(10)
print(z)

[ 0.42937294  1.49015546  1.74051795 -1.08715748 -0.60164334  0.20450953
  0.61181172 -1.25823077 -1.45192367 -1.54291764]


In [21]:
np.where(z > 0, z, 0)

array([0.42937294, 1.49015546, 1.74051795, 0.        , 0.        ,
       0.20450953, 0.61181172, 0.        , 0.        , 0.        ])